### ISSUE TITLE
とりあえず作る

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/paycover#1]
# TODO
* [x] Misocaフォーマットの請求管理kintoneアプリを作る
* [ ] Rails経由でkintoneにアップできるようにする（発行日（issue_date）、入金期日（payment_due_on）、添付）
* [ ] 支払いサイドを選べる（単発、毎月、15日と末日、など）
* [ ] 入金管理（支払う側、支払われる側共に）

**Comment by pandeiro245** [comment]
![image](https://cloud.githubusercontent.com/assets/125965/21933110/5aedf784-d9e7-11e6-98a7-998df32a1d0f.png)
